// <auto-generated />
namespace DataFilter.Wpf.Resources
{
    using System;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    public class FilterResources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilterResources()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataFilter.Wpf.Resources.FilterResources", typeof(FilterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sort A to Z.
        /// </summary>
        public static string AddSubSortAscending
        {
            get
            {
                return ResourceManager.GetString("AddSubSortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sort Z to A.
        /// </summary>
        public static string AddSubSortDescending
        {
            get
            {
                return ResourceManager.GetString("AddSubSortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add current selection to filter.
        /// </summary>
        public static string AddToFilter
        {
            get
            {
                return ResourceManager.GetString("AddToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Filter.
        /// </summary>
        public static string AdvancedFilter
        {
            get
            {
                return ResourceManager.GetString("AdvancedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Blanks).
        /// </summary>
        public static string Blanks
        {
            get
            {
                return ResourceManager.GetString("Blanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear
        {
            get
            {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingText
        {
            get
            {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok
        {
            get
            {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator:.
        /// </summary>
        public static string OperatorText
        {
            get
            {
                return ResourceManager.GetString("OperatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select All).
        /// </summary>
        public static string SelectAll
        {
            get
            {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort A to Z.
        /// </summary>
        public static string SortAscending
        {
            get
            {
                return ResourceManager.GetString("SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Z to A.
        /// </summary>
        public static string SortDescending
        {
            get
            {
                return ResourceManager.GetString("SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string ToText
        {
            get
            {
                return ResourceManager.GetString("ToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        public static string ValueText
        {
            get
            {
                return ResourceManager.GetString("ValueText", resourceCulture);
            }
        }
        
        public static string FilterOperator_Equals => ResourceManager.GetString("FilterOperator_Equals", resourceCulture);
        public static string FilterOperator_NotEquals => ResourceManager.GetString("FilterOperator_NotEquals", resourceCulture);
        public static string FilterOperator_Contains => ResourceManager.GetString("FilterOperator_Contains", resourceCulture);
        public static string FilterOperator_NotContains => ResourceManager.GetString("FilterOperator_NotContains", resourceCulture);
        public static string FilterOperator_StartsWith => ResourceManager.GetString("FilterOperator_StartsWith", resourceCulture);
        public static string FilterOperator_EndsWith => ResourceManager.GetString("FilterOperator_EndsWith", resourceCulture);
        public static string FilterOperator_GreaterThan => ResourceManager.GetString("FilterOperator_GreaterThan", resourceCulture);
        public static string FilterOperator_GreaterThanOrEqual => ResourceManager.GetString("FilterOperator_GreaterThanOrEqual", resourceCulture);
        public static string FilterOperator_LessThan => ResourceManager.GetString("FilterOperator_LessThan", resourceCulture);
        public static string FilterOperator_LessThanOrEqual => ResourceManager.GetString("FilterOperator_LessThanOrEqual", resourceCulture);
        public static string FilterOperator_Between => ResourceManager.GetString("FilterOperator_Between", resourceCulture);
        public static string FilterOperator_In => ResourceManager.GetString("FilterOperator_In", resourceCulture);
        public static string FilterOperator_NotIn => ResourceManager.GetString("FilterOperator_NotIn", resourceCulture);
        public static string FilterOperator_IsNull => ResourceManager.GetString("FilterOperator_IsNull", resourceCulture);
        public static string FilterOperator_IsNotNull => ResourceManager.GetString("FilterOperator_IsNotNull", resourceCulture);
        
        /// <summary>
        ///   Looks up a localized string similar to Add (OR).
        /// </summary>
        public static string ModeUnion => ResourceManager.GetString("ModeUnion", resourceCulture);
        
        /// <summary>
        ///   Looks up a localized string similar to Refine (AND).
        /// </summary>
        public static string ModeIntersection => ResourceManager.GetString("ModeIntersection", resourceCulture);
    }
}
